services:
  - type: web
    name: qissacafe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 --timeout 120 -b 0.0.0.0: backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_DEBUG
        value: 0
