-- ==============================================================================
-- QISSA CAFE — SUPABASE POSTGRESQL FULL DATABASE SCHEMA & SEED DATA
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Select your Project -> Click on "SQL Editor" in the left sidebar.
-- 3. Click "+ New Query", paste this entire script, and click "Run".
-- ==============================================================================

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create menu_items table
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL CHECK (price >= 0),
    description TEXT NOT NULL DEFAULT '',
    availability TEXT NOT NULL DEFAULT 'available' CHECK (availability IN ('available', 'low', 'sold_out')),
    sort_order INT NOT NULL DEFAULT 0,
    image TEXT NOT NULL DEFAULT '',
    is_veg BOOLEAN NOT NULL DEFAULT FALSE,
    is_bestseller BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code TEXT UNIQUE,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    order_type TEXT NOT NULL CHECK (order_type IN ('Takeaway', 'Dine-in', 'Delivery')),
    table_number TEXT NOT NULL DEFAULT '',
    delivery_address TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    total NUMERIC NOT NULL CHECK (total >= 0),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create order_items table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    menu_item_id BIGINT,
    item_name TEXT NOT NULL,
    unit_price NUMERIC NOT NULL,
    qty INT NOT NULL CHECK (qty > 0),
    line_total NUMERIC NOT NULL
);

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_order_code ON public.orders(order_code);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON public.menu_items(category);
CREATE INDEX IF NOT EXISTS idx_menu_items_sort_order ON public.menu_items(sort_order);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);

-- 7. Auto-update timestamp trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS trg_menu_items_updated_at ON public.menu_items;
CREATE TRIGGER trg_menu_items_updated_at
    BEFORE UPDATE ON public.menu_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trg_orders_updated_at ON public.orders;
CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 8. Enable Row Level Security (RLS)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 9. RLS Policies
-- Public read on settings and menu_items
DROP POLICY IF EXISTS "Allow public read access to settings" ON public.settings;
CREATE POLICY "Allow public read access to settings" ON public.settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service_role full access to settings" ON public.settings;

DROP POLICY IF EXISTS "Allow public read access to menu_items" ON public.menu_items;
CREATE POLICY "Allow public read access to menu_items" ON public.menu_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow full access to menu_items for service_role and anon" ON public.menu_items;

-- Orders are accessed only through the Flask backend. The server secret bypasses
-- RLS, so no anonymous order policies are required.
DROP POLICY IF EXISTS "Allow public order placement" ON public.orders;

DROP POLICY IF EXISTS "Allow public order tracking" ON public.orders;

DROP POLICY IF EXISTS "Allow full order management" ON public.orders;

DROP POLICY IF EXISTS "Allow public order_items placement" ON public.order_items;

DROP POLICY IF EXISTS "Allow public order_items reading" ON public.order_items;

DROP POLICY IF EXISTS "Allow full order_items management" ON public.order_items;

-- 10. Enable Supabase Realtime for instant updates
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        CREATE PUBLICATION supabase_realtime;
    END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.orders, public.menu_items, public.settings;

-- 11. Storage Bucket setup for Menu Images
INSERT INTO storage.buckets (id, name, public)
VALUES ('menu-images', 'menu-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access for Menu Images" ON storage.objects;
CREATE POLICY "Public Access for Menu Images" ON storage.objects
    FOR SELECT USING (bucket_id = 'menu-images');

DROP POLICY IF EXISTS "Allow Upload to Menu Images" ON storage.objects;

DROP POLICY IF EXISTS "Allow Update and Delete to Menu Images" ON storage.objects;

-- ==============================================================================
-- 12. INITIAL SEED DATA (Settings & 60+ Menu Items)
-- ==============================================================================

-- Settings
INSERT INTO public.settings (key, value) VALUES
('cafe_open', '1'),
('whatsapp', '919645700585'),
('address', 'Qissa Resto Cafe, Nilambur Road, Kerala'),
('opening_hours', '12:00 PM – 11:30 PM'),
('map_embed_url', 'https://maps.google.com/maps?q=11.1116412,76.2789462&t=&z=16&ie=UTF8&iwloc=&output=embed'),
('maps_directions_url', 'https://maps.app.goo.gl/5v2gcWyZ5xAjXJHV6'),
('menu_revision', '2026-08-31-v2'),
('bestseller_seeded', '1')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Menu Items
INSERT INTO public.menu_items (id, category, name, price, description, availability, sort_order, image, is_veg, is_bestseller) VALUES
(1, 'Shawarma', 'Shawarma Roll', 90, 'Classic Qissa shawarma roll.', 'available', 0, 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80', false, true),
(2, 'Shawarma', 'Shawarma Plate', 110, 'Shawarma served as a satisfying plate.', 'available', 1, 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=600&q=80', false, false),
(3, 'Shawarma', 'Full Meat Plate', 140, 'For when you want the full-meat experience.', 'available', 2, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80', false, false),
(4, 'Shawarma', 'Rumali Normal', 110, 'Soft rumali wrap with Qissa shawarma.', 'available', 3, 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80', false, false),
(5, 'Shawarma', 'Rumali Plate', 130, 'Rumali shawarma served as a plate.', 'available', 4, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80', false, false),
(6, 'Shawarma', 'Rumali Full Meat', 160, 'Premium full-meat rumali option.', 'available', 5, 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80', false, true),
(7, 'Broast', '2 Pcs Chicken Broast', 150, 'With kuboos, mayo dip, ketchup & fries.', 'available', 6, 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=600&q=80', false, true),
(8, 'Broast', '5 Pcs Chicken Broast', 250, 'With kuboos, mayo dip, ketchup & fries.', 'available', 7, 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80', false, false),
(9, 'Broast', '10 Pcs Chicken Broast', 500, 'Big broast box for sharing.', 'available', 8, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80', false, false),
(10, 'Burger', 'Vegetable Burger', 70, 'Veg patty, fresh layers and sauce.', 'available', 9, 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80', true, false),
(11, 'Burger', 'Egg Burger', 60, 'Simple, filling egg burger.', 'available', 10, 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80', false, false),
(12, 'Burger', 'Chicken Burger', 80, 'Qissa-style chicken burger.', 'available', 11, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', false, true),
(13, 'Burger', 'Chicken Nuggets Burger', 90, 'Crispy nuggets inside a soft bun.', 'available', 12, 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80', false, false),
(14, 'Burger', 'Chicken Double Decker', 120, 'A bigger double-layer chicken burger.', 'available', 13, 'https://images.unsplash.com/photo-1583032015879-c562e8477f1f?auto=format&fit=crop&w=600&q=80', false, true),
(15, 'Sandwich', 'Vegetable Sandwich', 40, 'Fresh and light veg sandwich.', 'available', 14, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80', true, false),
(16, 'Sandwich', 'Egg Sandwich', 40, 'Classic egg sandwich.', 'available', 15, 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80', false, false),
(17, 'Sandwich', 'Egg Cheese Sandwich', 50, 'Egg sandwich layered with cheese.', 'available', 16, 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?auto=format&fit=crop&w=600&q=80', false, false),
(18, 'Sandwich', 'Chicken Sandwich', 60, 'Tasty shredded chicken filling.', 'available', 17, 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80', false, false),
(19, 'Sandwich', 'Chicken Cheese Sandwich', 70, 'Chicken sandwich with melted cheese.', 'available', 18, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=600&q=80', false, false),
(20, 'Sandwich', 'Nuggets Sandwich', 60, 'Sandwich filled with nuggets.', 'available', 19, 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=600&q=80', false, false),
(21, 'Sandwich', 'Nuggets Cheese', 70, 'Nuggets sandwich with rich cheese.', 'available', 20, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=600&q=80', false, false),
(22, 'Sandwich', 'Chicken Club', 120, 'Generous triple-layer chicken club.', 'available', 21, 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?auto=format&fit=crop&w=600&q=80', false, false),
(23, 'Sandwich', 'Egg Club', 90, 'Triple-layer club with egg filling.', 'available', 22, 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=600&q=80', false, false),
(24, 'Sandwich', 'Veg Club', 80, 'Fresh veg club sandwich.', 'available', 23, 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80', true, false),
(25, 'Sandwich', 'Chicken Samoona', 50, 'Qissa-style samoona sandwich.', 'available', 24, 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80', false, false),
(26, 'Fried', 'Nuggets', 60, 'Crispy chicken bite snacks.', 'available', 25, 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80', false, false),
(27, 'Fried', 'Momos', 60, 'Steamed or fried bite-sized momos.', 'available', 26, 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80', false, false),
(28, 'Fried', 'French Fries', 60, 'Crisp golden salted potato fries.', 'available', 27, 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80', true, false),
(29, 'Fried', 'Cheesy Fries', 90, 'Fries smothered in warm cheese sauce.', 'available', 28, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80', true, false),
(30, 'Fried', 'Loaded Fries', 120, 'Fries topped with cheese, sauce and chicken.', 'available', 29, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80', false, false),
(31, 'Classic Shake', 'Mango Shake', 70, 'Creamy seasonal mango milkshake.', 'available', 30, 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80', true, false),
(32, 'Classic Shake', 'Chikku Shake', 70, 'Rich and smooth sapota shake.', 'available', 31, 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=600&q=80', true, false),
(33, 'Classic Shake', 'Apple Shake', 70, 'Fresh apple milkshake.', 'available', 32, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', true, false),
(34, 'Classic Shake', 'Avocado Shake', 80, 'Thick, buttery avocado butterfruit shake.', 'available', 33, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', true, false),
(35, 'Classic Shake', 'Tender Coconut Shake', 80, 'Sweet tender coconut pulp blended with milk.', 'available', 34, 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=600&q=80', true, false),
(36, 'Classic Shake', 'Badam Shake', 70, 'Classic almond badam flavoured shake.', 'available', 35, 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=600&q=80', true, false),
(37, 'Classic Shake', 'Dates Shake', 80, 'Natural sweet Arabian dates shake.', 'available', 36, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', true, false),
(38, 'Classic Shake', 'Strawberry Shake', 70, 'Sweet strawberry milkshake treat.', 'available', 37, 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80', true, false),
(39, 'Classic Shake', 'Vanilla Shake', 70, 'Smooth classic vanilla bean shake.', 'available', 38, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', true, false),
(40, 'Classic Shake', 'Oreo Shake', 80, 'Blended with crunchy Oreo cookies & cream.', 'available', 39, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', true, true),
(41, 'Falooda', 'Falooda', 90, 'Classic Qissa falooda with vermicelli and basil seeds.', 'available', 40, 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80', true, false),
(42, 'Falooda', 'White Falooda', 110, 'Special milk-forward white falooda.', 'available', 41, 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80', true, false),
(43, 'Falooda', 'Malabar Falooda', 120, 'Signature Malabar style dessert falooda.', 'available', 42, 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80', true, false),
(44, 'Falooda', 'Royal Falooda', 140, 'Loaded with nuts, fruits, and ice cream scoops.', 'available', 43, 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80', true, false),
(45, 'Falooda', 'Chocolate Falooda', 130, 'Rich cocoa and chocolate ice cream falooda.', 'available', 44, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', true, false),
(46, 'Mojito', 'Mint Mojito', 60, 'Classic muddled lime and fresh garden mint.', 'available', 45, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', true, false),
(47, 'Mojito', 'Watermelon Mojito', 70, 'Fresh watermelon cooler with mint.', 'available', 46, 'https://images.unsplash.com/photo-1587888637140-849b25d80ef9?auto=format&fit=crop&w=600&q=80', true, false),
(48, 'Mojito', 'Mango Mojito', 70, 'Tropical sweet mango sparkling mojito.', 'available', 47, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', true, false),
(49, 'Mojito', 'Orange Mojito', 70, 'Zesty citrus orange fizz.', 'available', 48, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80', true, false),
(50, 'Mojito', 'Litchi Mojito', 70, 'Exotic floral litchi refresher.', 'available', 49, 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=600&q=80', true, false),
(51, 'Mojito', 'Passion Fruit Mojito', 70, 'Tangy tropical passion fruit sparkle.', 'available', 50, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', true, false),
(52, 'Mojito', 'Green Apple Mojito', 70, 'Crisp green apple sour fizz.', 'available', 51, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', true, false),
(53, 'Soda', 'Lemon Soda', 30, 'Refreshing chilled lemon soda.', 'available', 52, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', true, false),
(54, 'Soda', 'Lemon Sweet & Salt', 30, 'Balanced sweet and salty lemon fizz.', 'available', 53, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80', true, false),
(55, 'Soda', 'Chilli Soda', 35, 'Spicy kick green chilli lime soda.', 'available', 54, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', true, false),
(56, 'Soda', 'Pine Soda', 40, 'Pineapple infused sparkling soda.', 'available', 55, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80', true, false),
(57, 'Soda', 'Grape Soda', 40, 'Dark grape fizzy cooler.', 'available', 56, 'https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=600&q=80', true, false),
(58, 'Soda', 'Orange Soda', 40, 'Tangy bright orange soda.', 'available', 57, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80', true, false),
(59, 'Lemon Juice', 'Fresh Lime', 20, 'Fresh lime juice.', 'available', 58, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', true, false),
(60, 'Lemon Juice', 'Sweet N Salt', 20, 'Classic sweet and salt lime.', 'available', 59, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80', true, false),
(61, 'Lemon Juice', 'Mint', 25, 'Refreshing mint lime.', 'available', 60, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', true, false),
(62, 'Lemon Juice', 'Pineapple Lime', 35, 'Pineapple-flavoured lime cooler.', 'available', 61, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80', true, false),
(63, 'Lemon Juice', 'Orange Lime', 35, 'Orange-flavoured lime cooler.', 'available', 62, 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80', true, false),
(64, 'Lemon Juice', 'Grape Lime', 35, 'Grape-flavoured lime cooler.', 'available', 63, 'https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=600&q=80', true, false),
(65, 'Lemon Juice', 'Blue Lime', 35, 'Refreshing blue lime cooler.', 'available', 64, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', true, true),
(66, 'Lemon Juice', 'Kashmiri Lime', 35, 'Qissa-style Kashmiri lime.', 'available', 65, 'https://images.unsplash.com/photo-1587888637140-849b25d80ef9?auto=format&fit=crop&w=600&q=80', true, false),
(67, 'Hot', 'Tea', 12, 'Traditional Kerala milk chai.', 'available', 66, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80', true, false),
(68, 'Hot', 'Coffee', 15, 'Rich brewed aromatic coffee.', 'available', 67, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80', true, false),
(69, 'Hot', 'Boost', 20, 'Hot malt chocolate Boost drink.', 'available', 68, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80', true, false),
(70, 'Hot', 'Horlicks', 20, 'Classic creamy hot Horlicks.', 'available', 69, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80', true, false),
(71, 'Hot', 'Black Tea', 12, 'Plain black tea.', 'available', 70, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80', true, false),
(72, 'Hot', 'Black Tea Mint', 15, 'Mint-infused hot black tea.', 'available', 71, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80', true, false),
(73, 'Hot', 'Black Lemon', 15, 'Black tea with a squeeze of fresh lemon.', 'available', 72, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80', true, false),
(74, 'Hot', 'Green Tea', 20, 'Fresh hot green tea.', 'available', 73, 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=600&q=80', true, false)
ON CONFLICT (id) DO UPDATE SET
    category = EXCLUDED.category,
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    description = EXCLUDED.description,
    availability = EXCLUDED.availability,
    sort_order = EXCLUDED.sort_order,
    image = EXCLUDED.image,
    is_veg = EXCLUDED.is_veg,
    is_bestseller = EXCLUDED.is_bestseller;

-- Reset sequence to highest ID
SELECT setval(pg_get_serial_sequence('public.menu_items', 'id'), COALESCE(MAX(id), 1)) FROM public.menu_items;
