SEED_MENU = [{'id': 1,
  'category': 'Shawarma',
  'name': 'Shawarma Roll',
  'price': 90,
  'description': 'Classic Qissa shawarma roll.',
  'availability': 'available'},
 {'id': 2,
  'category': 'Shawarma',
  'name': 'Shawarma Plate',
  'price': 110,
  'description': 'Shawarma served as a satisfying plate.',
  'availability': 'available'},
 {'id': 3,
  'category': 'Shawarma',
  'name': 'Full Meat Plate',
  'price': 140,
  'description': 'For when you want the full-meat experience.',
  'availability': 'available'},
 {'id': 4,
  'category': 'Shawarma',
  'name': 'Rumali Normal',
  'price': 110,
  'description': 'Soft rumali wrap with Qissa shawarma.',
  'availability': 'available'},
 {'id': 5,
  'category': 'Shawarma',
  'name': 'Rumali Plate',
  'price': 130,
  'description': 'Rumali shawarma served as a plate.',
  'availability': 'available'},
 {'id': 6,
  'category': 'Shawarma',
  'name': 'Rumali Full Meat',
  'price': 160,
  'description': 'Premium full-meat rumali option.',
  'availability': 'available'},
 {'id': 7,
  'category': 'Broast',
  'name': '2 Pcs Chicken Broast',
  'price': 150,
  'description': 'With kuboos, mayo dip, ketchup & fries.',
  'availability': 'available'},
 {'id': 8,
  'category': 'Broast',
  'name': '5 Pcs Chicken Broast',
  'price': 250,
  'description': 'With kuboos, mayo dip, ketchup & fries.',
  'availability': 'available'},
 {'id': 9,
  'category': 'Broast',
  'name': '10 Pcs Chicken Broast',
  'price': 500,
  'description': 'Big broast box for sharing.',
  'availability': 'available'},
 {'id': 10,
  'category': 'Burger',
  'name': 'Vegetable Burger',
  'price': 70,
  'description': 'Veg patty, fresh layers and sauce.',
  'availability': 'available'},
 {'id': 11,
  'category': 'Burger',
  'name': 'Egg Burger',
  'price': 60,
  'description': 'Simple, filling egg burger.',
  'availability': 'available'},
 {'id': 12,
  'category': 'Burger',
  'name': 'Chicken Burger',
  'price': 80,
  'description': 'Qissa-style chicken burger.',
  'availability': 'available'},
 {'id': 13,
  'category': 'Burger',
  'name': 'Chicken Nuggets Burger',
  'price': 90,
  'description': 'Crispy nuggets inside a soft bun.',
  'availability': 'available'},
 {'id': 14,
  'category': 'Burger',
  'name': 'Chicken Double Decker',
  'price': 120,
  'description': 'A bigger double-layer chicken burger.',
  'availability': 'available'},
 {'id': 15,
  'category': 'Sandwich',
  'name': 'Vegetable Sandwich',
  'price': 40,
  'description': 'Fresh and light veg sandwich.',
  'availability': 'available'},
 {'id': 16,
  'category': 'Sandwich',
  'name': 'Egg Sandwich',
  'price': 40,
  'description': 'Classic egg sandwich.',
  'availability': 'available'},
 {'id': 17,
  'category': 'Sandwich',
  'name': 'Egg Cheese Sandwich',
  'price': 50,
  'description': 'Egg sandwich with cheese.',
  'availability': 'available'},
 {'id': 18,
  'category': 'Sandwich',
  'name': 'Chicken Sandwich',
  'price': 50,
  'description': 'Quick chicken sandwich.',
  'availability': 'available'},
 {'id': 19,
  'category': 'Sandwich',
  'name': 'Chicken Cheese Sandwich',
  'price': 60,
  'description': 'Chicken with a cheesy finish.',
  'availability': 'available'},
 {'id': 20,
  'category': 'Sandwich',
  'name': 'Nuggets Sandwich',
  'price': 60,
  'description': 'Crispy nuggets sandwich.',
  'availability': 'available'},
 {'id': 21,
  'category': 'Sandwich',
  'name': 'Nuggets Cheese',
  'price': 70,
  'description': 'Nuggets sandwich with cheese.',
  'availability': 'available'},
 {'id': 22,
  'category': 'Sandwich',
  'name': 'Chicken Club',
  'price': 130,
  'description': 'Loaded multi-layer club sandwich.',
  'availability': 'available'},
 {'id': 23,
  'category': 'Sandwich',
  'name': 'Egg Club',
  'price': 80,
  'description': 'Egg club sandwich.',
  'availability': 'available'},
 {'id': 24,
  'category': 'Sandwich',
  'name': 'Veg Club',
  'price': 100,
  'description': 'Layered vegetarian club sandwich.',
  'availability': 'available'},
 {'id': 25,
  'category': 'Sandwich',
  'name': 'Chicken Samoona',
  'price': 50,
  'description': 'Chicken filling in a samoona bun.',
  'availability': 'available'},
 {'id': 26,
  'category': 'Fried',
  'name': 'Nuggets',
  'price': 80,
  'description': 'Crispy bite-size chicken nuggets.',
  'availability': 'available'},
 {'id': 27,
  'category': 'Fried',
  'name': 'Momos',
  'price': 80,
  'description': 'Hot, tasty momos.',
  'availability': 'available'},
 {'id': 28,
  'category': 'Fried',
  'name': 'French Fries',
  'price': 60,
  'description': 'Golden and crispy fries.',
  'availability': 'available'},
 {'id': 29,
  'category': 'Fried',
  'name': 'Cheesy Fries',
  'price': 100,
  'description': 'Fries with a cheesy topping.',
  'availability': 'available'},
 {'id': 30,
  'category': 'Fried',
  'name': 'Loaded Fries',
  'price': 130,
  'description': 'Fully loaded fries for serious cravings.',
  'availability': 'available'},
 {'id': 31,
  'category': 'Classic Shake',
  'name': 'Mango Shake',
  'price': 70,
  'description': 'Classic chilled mango shake.',
  'availability': 'available'},
 {'id': 32,
  'category': 'Classic Shake',
  'name': 'Chikku Shake',
  'price': 70,
  'description': 'Creamy chikku shake.',
  'availability': 'available'},
 {'id': 33,
  'category': 'Classic Shake',
  'name': 'Apple Shake',
  'price': 70,
  'description': 'Fresh apple milkshake.',
  'availability': 'available'},
 {'id': 34,
  'category': 'Classic Shake',
  'name': 'Avocado Shake',
  'price': 80,
  'description': 'Rich and creamy avocado.',
  'availability': 'available'},
 {'id': 35,
  'category': 'Classic Shake',
  'name': 'Tender Coconut Shake',
  'price': 80,
  'description': 'Tender coconut blended smooth.',
  'availability': 'available'},
 {'id': 36,
  'category': 'Classic Shake',
  'name': 'Badam Shake',
  'price': 70,
  'description': 'Nutty badam shake.',
  'availability': 'available'},
 {'id': 37,
  'category': 'Classic Shake',
  'name': 'Dates Shake',
  'price': 70,
  'description': 'Naturally sweet dates shake.',
  'availability': 'available'},
 {'id': 38,
  'category': 'Classic Shake',
  'name': 'Strawberry Shake',
  'price': 70,
  'description': 'Creamy strawberry shake.',
  'availability': 'available'},
 {'id': 39,
  'category': 'Classic Shake',
  'name': 'Vanilla Shake',
  'price': 70,
  'description': 'Smooth classic vanilla.',
  'availability': 'available'},
 {'id': 40,
  'category': 'Falooda',
  'name': 'Falooda',
  'price': 80,
  'description': 'Classic chilled falooda.',
  'availability': 'available'},
 {'id': 41,
  'category': 'Falooda',
  'name': 'White Falooda',
  'price': 90,
  'description': 'Creamy white falooda.',
  'availability': 'available'},
 {'id': 42,
  'category': 'Falooda',
  'name': 'Malabar Falooda',
  'price': 100,
  'description': 'A richer Malabar-style falooda.',
  'availability': 'available'},
 {'id': 43,
  'category': 'Falooda',
  'name': 'Royal Falooda',
  'price': 100,
  'description': 'Royal falooda with a premium finish.',
  'availability': 'available'},
 {'id': 44,
  'category': 'Falooda',
  'name': 'Chocolate Falooda',
  'price': 100,
  'description': 'Chocolate meets classic falooda.',
  'availability': 'available'},
 {'id': 45,
  'category': 'Mojito',
  'name': 'Mint Mojito',
  'price': 70,
  'description': 'Cool mint refreshment.',
  'availability': 'available'},
 {'id': 46,
  'category': 'Mojito',
  'name': 'Watermelon Mojito',
  'price': 70,
  'description': 'Fresh watermelon cooler.',
  'availability': 'available'},
 {'id': 47,
  'category': 'Mojito',
  'name': 'Mango Mojito',
  'price': 70,
  'description': 'Fruity mango refreshment.',
  'availability': 'available'},
 {'id': 48,
  'category': 'Mojito',
  'name': 'Orange Mojito',
  'price': 70,
  'description': 'Bright citrus cooler.',
  'availability': 'available'},
 {'id': 49,
  'category': 'Mojito',
  'name': 'Litchi Mojito',
  'price': 70,
  'description': 'Sweet litchi refresher.',
  'availability': 'available'},
 {'id': 50,
  'category': 'Mojito',
  'name': 'Passion Fruit Mojito',
  'price': 70,
  'description': 'Tropical passion fruit cooler.',
  'availability': 'available'},
 {'id': 51,
  'category': 'Mojito',
  'name': 'Green Apple Mojito',
  'price': 70,
  'description': 'Tangy green apple fizz.',
  'availability': 'available'},
 {'id': 52,
  'category': 'Soda',
  'name': 'Lemon Soda',
  'price': 15,
  'description': 'Classic lemon soda.',
  'availability': 'available'},
 {'id': 53,
  'category': 'Soda',
  'name': 'Lemon Sweet & Salt',
  'price': 15,
  'description': 'Sweet, salty and refreshing.',
  'availability': 'available'},
 {'id': 54,
  'category': 'Soda',
  'name': 'Chilli Soda',
  'price': 20,
  'description': 'A spicy soda kick.',
  'availability': 'available'},
 {'id': 55,
  'category': 'Soda',
  'name': 'Pine Soda',
  'price': 30,
  'description': 'Pineapple soda cooler.',
  'availability': 'available'},
 {'id': 56,
  'category': 'Soda',
  'name': 'Grape Soda',
  'price': 30,
  'description': 'Fizzy grape refreshment.',
  'availability': 'available'},
 {'id': 57,
  'category': 'Soda',
  'name': 'Orange Soda',
  'price': 30,
  'description': 'Bright orange soda.',
  'availability': 'available'},
 {'id': 58, 'category': 'Hot', 'name': 'Tea', 'price': 12, 'description': 'Hot tea.', 'availability': 'available'},
 {'id': 59,
  'category': 'Hot',
  'name': 'Coffee',
  'price': 15,
  'description': 'Hot coffee.',
  'availability': 'available'},
 {'id': 60, 'category': 'Hot', 'name': 'Boost', 'price': 20, 'description': 'Hot Boost.', 'availability': 'available'},
 {'id': 61,
  'category': 'Hot',
  'name': 'Horlicks',
  'price': 20,
  'description': 'Hot Horlicks.',
  'availability': 'available'},
 {'id': 62,
  'category': 'Hot',
  'name': 'Black Tea',
  'price': 12,
  'description': 'Simple black tea.',
  'availability': 'available'},
 {'id': 63,
  'category': 'Hot',
  'name': 'Black Tea Mint',
  'price': 15,
  'description': 'Black tea with mint.',
  'availability': 'available'},
 {'id': 66,
  'category': 'Hot',
  'name': 'Green Tea',
  'price': 20,
  'description': 'Fresh hot green tea.',
  'availability': 'available'},
 {'id': 65,
  'category': 'Hot',
  'name': 'Black Lemon',
  'price': 15,
  'description': 'Hot black lemon drink.',
  'availability': 'available'},
 {'id': 67,
  'category': 'Lemon Juice',
  'name': 'Fresh Lime',
  'price': 20,
  'description': 'Fresh lime juice.',
  'availability': 'available'},
 {'id': 68,
  'category': 'Lemon Juice',
  'name': 'Sweet N Salt',
  'price': 20,
  'description': 'Classic sweet and salt lime.',
  'availability': 'available'},
 {'id': 69,
  'category': 'Lemon Juice',
  'name': 'Mint',
  'price': 25,
  'description': 'Refreshing mint lime.',
  'availability': 'available'},
 {'id': 70,
  'category': 'Lemon Juice',
  'name': 'Pineapple Lime',
  'price': 35,
  'description': 'Pineapple-flavoured lime cooler.',
  'availability': 'available'},
 {'id': 71,
  'category': 'Lemon Juice',
  'name': 'Orange Lime',
  'price': 35,
  'description': 'Orange-flavoured lime cooler.',
  'availability': 'available'},
 {'id': 72,
  'category': 'Lemon Juice',
  'name': 'Grape Lime',
  'price': 35,
  'description': 'Grape-flavoured lime cooler.',
  'availability': 'available'},
 {'id': 73,
  'category': 'Lemon Juice',
  'name': 'Blue Lime',
  'price': 35,
  'description': 'Refreshing blue lime cooler.',
  'availability': 'available'},
 {'id': 74,
  'category': 'Lemon Juice',
  'name': 'Kashmiri Lime',
  'price': 35,
  'description': 'Qissa-style Kashmiri lime.',
  'availability': 'available'}]
